version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - uploads:/app/uploads
      - outputs:/app/outputs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
    restart: unless-stopped
    networks:
      - csv-analyzer-network

networks:
  csv-analyzer-network:
    driver: bridge

volumes:
  uploads:
  outputs:
